## 실행 명령어: python main_skeleton.py recognition -c config/ntu60_xsub/test_joint.yaml

work_dir: /home/zio/data/dtaas/final_test             # test 결과 저장 경로
weights: /home/zio/data/dtaas/final/epoch14_model.pt  # test하는 model 경로

# feeder
feeder: feeder.feeder_skeleton.Feeder
test_feeder_args:
  centralization: False
  if_bone: False
  data_path: /home/zio/mocap/preprocessed_final/xsub/val_data_joint.npy    # test dataset 경로
  label_path: /home/zio/mocap/preprocessed_final/xsub/val_label.pkl

# model
model: net.gcn.Model
model_args:
  in_channels: 3
  num_class: 63
  dropout: 0.5
  edge_importance_weighting: False
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
phase: test
device: [0,1,2,3,4] # 본인의 GPU 개수에 따라 변경 필요함.
test_batch_size: 8

# save
save_result: True
