# python main_skeleton.py recognition -c config/ntu60_xsub/train_bone.yaml
work_dir: /home/zio/data/dtaas/final_bone_2

# feeder
feeder: feeder.feeder_skeleton.Feeder
train_feeder_args:
  centralization: False
  random_move: False
  if_bone: False
  data_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/230106_Final/xsub/train_data_bone.npy
  label_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/230106_Final/xsub/train_label.pkl
test_feeder_args:
  centralization: False
  if_bone: False
  data_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/230106_Final/xsub/val_data_bone.npy
  label_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/230106_Final/xsub/val_label.pkl

# model
model: net.gcn.Model
model_args:
  in_channels: 3
  num_class: 63
  dropout: 0.5
  edge_importance_weighting: False
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0,1,2,3,4]
batch_size: 8
test_batch_size: 8
num_epoch: 21
